### ISSUE TITLE
No thumbnails for uncompressed DDS

### ISSUE THREAD

**Issue by vic-bay** [meyraud705/dds10-thumbnailer-kde#1]
Exported an uncompressed DDS from GIMP (compression method None, no mipmaps) and there are no thumbnails for the image. The dds seems to be correct, as I can import it back to GIMP, and convert it with imagemagick, and open it with display utility from imagemagic package. 
CC0 texture that has no thumbnail:
[aerial_rocks_02_diff_1k_uncompressed.zip](https://github.com/meyraud705/dds10-thumbnailer-kde/files/12686629/aerial_rocks_02_diff_1k_uncompressed.zip)

**Comment by meyraud705** [comment]
Only compressed DDS are supported for now. But adding support for uncompressed RGBA format should not be that hard, just need to skip decompression step. I'll take a look at this.

**Comment by meyraud705** [comment]
Support for some uncompressed format added in c2f3a7e.
Supported and tested: RGB8, RGBA8, A8, L8 and RGB565.
Supported but not tested: RGBX8, RGBX4, RGBX5551, L16.

**Comment by vic-bay** [comment]
thanks for fast update, everything looks fine :+1:
